"""initial schema

Revision ID: 677d48ed2138
Revises: 
Create Date: 2026-06-17 05:12:02.690456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677d48ed2138'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('target_exam', sa.Enum('JEE', 'NEET', 'CAT', 'GATE', 'SSC', 'UPSC', 'IBPS', name='examtype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leaderboard',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exam_type', sa.Enum('JEE', 'NEET', 'CAT', 'GATE', 'SSC', 'UPSC', 'IBPS', name='examtype'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exam_type', sa.Enum('JEE', 'NEET', 'CAT', 'GATE', 'SSC', 'UPSC', 'IBPS', name='examtype'), nullable=False),
    sa.Column('mode', sa.Enum('FULL_TEST', 'SUBJECT_TEST', 'CHAPTER_TEST', 'QUICK', name='testmode'), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('chapter', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'MIXED', name='difficulty'), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'ABANDONED', name='sessionstatus'), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('time_per_q', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('exam_type', sa.Enum('JEE', 'NEET', 'CAT', 'GATE', 'SSC', 'UPSC', 'IBPS', name='examtype'), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.Column('unattempted', sa.Integer(), nullable=False),
    sa.Column('time_taken_mins', sa.Float(), nullable=False),
    sa.Column('topic_accuracy', sa.JSON(), nullable=True),
    sa.Column('weak_topics', sa.JSON(), nullable=True),
    sa.Column('time_analysis', sa.JSON(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('predicted_rank', sa.Integer(), nullable=True),
    sa.Column('ai_coach_report', sa.Text(), nullable=True),
    sa.Column('solutions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('test_sessions')
    op.drop_table('leaderboard')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
